# Generated by Django 2.0.4 on 2018-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneMasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=150)),
                ('property_address_1', models.CharField(max_length=150)),
                ('property_address_2', models.CharField(max_length=150)),
                ('property_address_3', models.CharField(max_length=150)),
                ('property_address_4', models.CharField(max_length=150)),
                ('unit_name', models.CharField(max_length=150)),
                ('tenant_name', models.CharField(max_length=150)),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('lease_years', models.IntegerField()),
                ('current_rent', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
