# Generated by Django 2.0.4 on 2018-04-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneMasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemasts',
            name='lease_end_date',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='phonemasts',
            name='lease_start_date',
            field=models.CharField(max_length=25),
        ),
    ]
